const quotes = [
    "Cuando pierdas, no pierdas la lección. Dalai Lama",
    "Sueña como si fueras a vivir para siempre, vive como si fueses a morir hoy. James Dean",
    "Sé amable, porque toda persona que conoces está librando una gran batalla. Platón",
    "Sé tú mismo. Todos los demás ya están ocupados. Oscar Wilde",
    "Tu tiempo es limitado así que no lo malgastes en la vida de los demás. Steve Jobs",
    "La felicidad no está en lo que tú tienes sino en tu actitud.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido. George Eliot",
    "No tienes que ser grande para empezar. Pero tienes que empezar para poder ser grande. Zig Ziglar",
    "Si te caíste ayer, levántate hoy. H.G. Wells",
    "Tienes el poder de crear la vida de tus sueños",
    "Lo que no te mata, te hace más fuerte. Friedrich Nietzsche",
    "La cuestión no es quién va a permitírmelo, sino quién va a ser capaz de pararme. Ayn Rand",
    "Los dos guerreros más poderosos son la paciencia y el tiempo.",
    "No se trata de si van a derribarte, se trata de si vas a levantarte cuando lo hagan. Vince Lombardi",
    "Nadie puede hacerte sentir inferior sin tu consentimiento. Eleanor Roosevelt",
    "Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo. Ana Frank",
    "El pesimista ve dificultades en cada oportunidad. El optimista ve oportunidades en cada dificultad. Winston Churchill",
    "Muchos piensan en cambiar el mundo, pero casi nadie piensa en cambiarse a sí mismo. Leon Tolstoi",
    "No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo. Robin Williams",
    "Eres tan increíble como te dejas serlo.",
    "Das lo que eres, no lo que recibes.",
    "La suerte para triunfar en la vida se llama: creer en ti.",
    "Ser buen perdedor es aprender como ganar. Carl Sandburg",
    "Lo único imposible es aquello que no intentas.",
    "A partir de hoy, me cuidaré como siempre me he merecido.",
    "Querer ser otra persona es malgastar la persona que eres.",
    "Mi opinión es igual de importante que la de los demás.",
    "Quién mira afuera, sueña: quién mira adentro, despierta.",
    "Caerse está permitido, levantarse es obligatorio.",
    "Soy mi musa, mi propia obra de arte.",
    "Siempre sé la mejor versión de ti mismo, y la segunda mejor versión de todos los demás. Judy Garland",
    "Hecho es mejor que perfecto. Sheryl Sandberg",
    "Si no te gustan las cosas, ¡cámbialas! No eres un árbol. Jim Rohn",
    "Las oportunidades no pasan. Las creas. Chris Grosser",
    "Las ideas no duran mucho. Hay que hacer algo con ellas. Santiago Ramón y Cajal",
    "Para tener éxito la actitud es tan importante como la habilidad. Walter Scott",
    "Un objetivo sin un plan es solo un deseo. Antoine de Saint-Exupéry",
    "El secreto para salir adelante es comenzar. Mark Twain",
    "No tengas miedo de abandonar lo bueno para ir a por lo grandioso. John D. Rockefeller",
    "Cuanto más duramente trabajo, más suerte tengo. Gary Player",
    "El fracaso es una buena oportunidad para empezar de nuevo con más inteligencia.",
    "La diferencia entre lo ordinario y lo extraordinario es un poquito de esfuerzo. Jimmy Johnson",
    "No he llegado tan lejos solo para llegar hasta aquí.",
    "Nunca soñé con el éxito. Trabajé por él. Estée Lauder",
    "No puede cambiar su destino de la noche a la mañana, pero puede cambiar su dirección de la noche a la mañana. Jim Rohn",
    "Si tú sabes lo que vales, ve y consigue lo que mereces. Rocky Balboa",
    "Si estás trabajando en algo que te importa de verdad, nadie tiene que empujarte: tu visión te empuja. Steve Jobs",
    "El único modo de hacer un gran trabajo es amar lo que haces. Steve Jobs",
    "La excelencia no es un acto, es un hábito. Aristóteles",
    "Da siempre lo mejor que tienes. Lo que plantes ahora, lo cosecharás más tarde. Og Mandino",
    "Si crees que puedes, ya estás a medio camino. Theodore Roosevelt",
    "Todos tus sueños se harán realidad si tienes el coraje de perseguirlos. Walt Disney",
    "Si no puedes tolerar a los críticos, no haga nada nuevo o interesante. Jeff Bezos",
    "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado. Proverbio africano",
    "La verdadera motivación procede de trabajar en cosas que nos importan. Sheryl Sandberg",
    "Deja marcado en tu corazón que cada día es el mejor día del año. Ralph Waldo Emerson",
    "El amor no necesita ser entendido, simplemente necesita ser demostrado. Paulo Cohelo",
    "La medida del amor es amar sin medida. San Agustín",
    "El amor es tan importante como la comida. Gabriel García Marquez",
    "Si cuando amo soy feliz, entonces eres mi felicidad.",
    "Lo que se hace por amor está más allá del bien y del mal. Friedrich Nietzsche",
    "Estar enamorado de alguien te da fuerzas, mientras que amar a alguien te da coraje. Lao Tzu",
    "Nos sentimos más vivos cuando estamos enamorados. John Updike",
    "¿Y si este amor fuera más fuerte que la gravedad?.",
    "Tardé un minuto en conocerte, pero me tomará toda una vida poder llegar a olvidarte.",
    "Quien ama puede estar equivocado de sujeto pero nunca de verbo.",
    "Algunas veces el amor de tu vida viene después del error de tu vida.",
    "La vida es una flor y el amor es su miel. Víctor Hugo",
    "El amor está compuesto por un alma habitando dos cuerpos. Aristóteles",
    "El amor no necesita ser perfecto, sólo necesita ser verdadero.",
    "Dale a cada día la oportunidad de ser el día más hermoso de tu vida. Mark Twain",
    "Avanza con confianza en la dirección de tus sueños. Thoreau",
    "Contigo, todo es posible.",
    "La gratitud es la memoria del corazón.",
    "No te busques, no te encuentres. Constrúyete.",
    "No sueñes tu vida, vive tu sueño.",
    "Objetivos para hoy: café y cariño, Bueno, que sean 2 tazas de café y luego cariño.",
    "Debes hacer las cosas que crees que no puedes hacer.",
    "Lo mejor está por venir.",
    "Sin lluvia no habría arcoiris.",
    "No quiero ganarme la vida, quiero vivir.  Oscar Wilde",
    "Trae tu propio sol.",
    "Poder decir adiós es crecer.",
    "Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta. Henry Ford",
    "El conocimiento es poder. Francis Bacon",
    "Dale a cada día la posibilidad de ser el mejor día de tu vida.",
    "Va a pasar, porque tú vas a hacer que pase.",
    "Todo lo que se puede imaginar es real. Pablo Picasso",
    "Podemos sufrir muchas derrotas pero no debemos ser derrotados. Maya Angelou",
    "Da el primer paso con fe. No tienes que ver todas las escaleras, solo da el primer paso. Martin Luther King",
    "No importa lo lento que vayas, siempre y cuando no te detengas.",
    "Si te caes tres veces, levántate cuatro.",
    "Sí puedes. Siempre puedes.",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre. Mahatma Gandhi",
    "La única diferencia entre un buen y un mal día es tu actitud.",
    "Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí. Carol Burnett",
    "No cuentes los días, haz que los días cuenten. Muhammad Ali",
    "El amor no tiene cura, pero es la cura para todos los males. Leonard Cohen",
    "El mejor momento del día es ahora. Pierre Bonnard",
    "Sé el cambio que quieres ver en el mundo. Mahatma Gandhi",
    "Piensa, sueña, cree y atrévete. Walt Disney",
    "No pares cuando estés cansado. Para cuando hayas terminado. Marilyn Monroe",
    "El sentido de la vida es tener valores, no cosas de valor.",
    "Cree que puedes y casi lo habrás logrado. Theodore Roosevelt",
    "Vayas donde vayas, ve con todo tu corazón. Confucio",
    "La mejor forma de predecir el futuro es creándolo. Peter Druker​",
    "Solo imagina lo precioso que puede ser arriesgarse y que todo salga bien. Mario Benedetti",
    "El que tiene un porqué para vivir, puede soportar casi cualquier cómo. Viktor Frankl",
    "Si quieres cambiar el mundo, cámbiate a ti mismo. Mahatma Ghandi",
    "Camina hacia el sol y las sombras quedarán siempre tras de ti. Walt Whitman",
    "La vida no se trata de encontrarte a ti mismo, sino de crearte a ti mismo. Bernard Shaw",
    "Alguien se sienta en una sombra hoy porque alguien plantó un árbol hace mucho tiempo. Warren Buffet",
    "La felicidad no ocurre por casualidad, sino por elección. Jim Rohn",
    "Convierte cada día en tu obra maestra. John Wooden",
    "La creatividad es la inteligencia divirtiéndose. Albert Einstein",
    "Vive la vida que amas. Ama la vida que vives. Bob Marley",
    "La verdadera felicidad consiste en hacer el bien. Aristóteles",
    "Háblate a ti mismo como harías con alguien a quien amas. Brene Brown",
    "Una buena caminata por la mañana es una bendición para el resto del día. Henry David Thoreau",
    "Cada día me despierto diciéndome que estoy vivo, y que eso es un milagro. Jim Carrey",
    "Nada de lo que vistes es más importante que tu sonrisa. Connie Stevens​",
    "Vivir es nacer a cada instante. Erich Fromm",
    "La lógica te llevará de la A a la Z. La imaginación te llevará a cualquier lugar. Albert Einstein",
    "Ha llegado el momento de vivir la vida que imaginaste. Henry James",
    "La vida debe ser comprendida hacia detrás, pero debe ser vivida hacia delante. Kierkegard",
    "No lastimes a los demás con lo que te causa dolor a ti mismo. Buda",
    "La felicidad no brota de la razón, sino de la imaginación. Kant",
    "En la vida hay algo peor que el fracaso, no haberlo intentado. Roosevelt",
    "Cuando haya una voz en tu cabeza que te diga que no puedes pintar, pinta tanto como puedas y verás cómo se callará. Van Gogh",
    "Apunta a la luna. Si fallas, podrías dar a una estrella. William Clement Stone",
    "Cuando pierdas, no pierdas la lección. Dalai Lama",
    "El futuro pertenece a aquellos que creen en la belleza de sus sueños. Eleanor Roosevelt",
    "Transforma tus heridas en sabiduría. Oprah Winfrey",
    "Si puedes soñarlo, puedes hacerlo. Walt Disney",
    "No dejes que tu pasado ocupe todo tu presente. Will Rogers​",
    "A un hombre le pueden robar todo, menos una cosa, la última de las libertades del ser humano, la elección de su propia actitud ante cualquier tipo de circunstancias, la elección del propio camino. Viktor Frankl",
    "La energía y la persistencia conquistan todas las cosas. Benjamin Franklin",
    "Lo que importa no es lo que te ocurre, sino cómo reaccionas a ello. Epicteto",
    "Nuestra mayor gloria no es no caer nunca, sino levantarnos cada vez que nos caemos. Confucio",
    "El momento en que quieres dejarlo es justo el momento en que tienes que seguir avanzando. Anónimo",
    "Nunca eres demasiado viejo para marcarte otra meta o tener un nuevo sueño. C.S. Lewis",
    "No esperes. Nunca va a ser el momento adecuado. Napoleon Hill",
    "La vida es en un 10% lo que te ocurre, y en un 90% cómo te lo tomas. Charles R. Swindoll",
    "A veces no conoces el valor de un momento hasta que se ha convertido en un recuerdo. Dr. Seuss",
    "Te deseo que estés vivo cada día de tu vida. Jonathan Swift",
    "Hay dos grandes días en la vida de una persona: el día en que nacemos y el día en que descubrimos para qué. William Barclay",
    "Un viaje de 1000 paso da comienzo con un solo primer paso. Lao Tzu",
    "Dentro de un año desearás haber empezado hoy. Karen Lamb",
    "Solo se vive una vez. Pero si lo haces bien, una vez basta. Mae West",
    "La buena vida es una forma de pensar. Emilio Valcárcel",
    "No es la muerte lo que debes temer, sino nunca empezar a vivir. Marco Aurelio",
    "La mejor venganza es un éxito sin parangón. Frank Sinatra",
    "El que pasa el tiempo arrepintiéndose del pasado, pierde el presente y arriesga el futuro. —Francisco de Quevedo",
    "La vida es como montar en bicicleta. Para mantener el equilibrio tienes que avanzar. Albert Einstein",
    "Lo que hagas hoy puede mejorar el resto de tus mañanas. Ralph Marston",
    "El tiempo que disfrutar perder no es tiempo perdido. Marthe Troly-Curtin",
    "El optimismo puede ser más poderoso que un escuadrón de tanques. General Rick Hillier​",
]

/**
 * Gets a random Piñera Quote
 * @returns {string}
 */
function randomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}

module.exports = {
  randomQuote
};